# Site settings
title: Cybersecurity Theatre
email: kinlane@gmail.com
url:  http://cybersecurity.theater
baseurl: ""
description: "A cybersecurity production."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  accent: purple
  highlight: yellow

# Footer settings
footer: Cybersecurity Theatre

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/kinlane
  - title: facebook
    url: https://facebook.com/kinlane
  - title: instagram
    url: https://instagram.com/kinlane

# Build settings
markdown: kramdown
permalink: pretty
